services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./utils/recipes/Dockerfile_app
    volumes:
      - .:/app
    ports:
      - "8002:80"
    environment:
      - SERVER_NAME=:80
  database:
    container_name: cyber-tp5-database
    image: mariadb:10.5.8
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: studoo
      #MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      #MYSQL_USER: app_db_user
      #MYSQL_PASSWORD: app_db_password
    volumes:
      - ./var/dbdata:/var/lib/mysql
      - ./docs/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    container_name: cyber-tp5-pma
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 0
    restart: always
    links:
      - database